# Generated by Django 3.1.7 on 2021-03-19 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0011_auto_20210319_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 19, 2, 19, 9278, tzinfo=utc)),
        ),
    ]
